services:
  mssql-test:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: wferp-mssql-test
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Passw0rd!234"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./init:/init
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P Passw0rd!234 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
